from enum import Enum

class TrustClassification(str, Enum):
    CLEAN_EXPORT = "CLEAN_EXPORT"
    EXPORT_WITH_WARNINGS = "EXPORT_WITH_WARNINGS"
    PARTIAL_EXPORT = "PARTIAL_EXPORT"
    UNSAFE_EXPORT = "UNSAFE_EXPORT"
    EXPORT_EMBARGO = "EXPORT_EMBARGO"
