from enum import Enum


class ReconciliationStatus(Enum):
    MATCH = "MATCH"
    MATCH_WITH_TOLERANCE = "MATCH_WITH_TOLERANCE"
    MISMATCH = "MISMATCH"
    MISSING_EXPECTED = "MISSING_EXPECTED"
    MISSING_ACTUAL = "MISSING_ACTUAL"
    UNRECONCILABLE = "UNRECONCILABLE"